### ISSUE TITLE
Dependency on rsync not advertised

### ISSUE THREAD

**Issue by saalaa** [gordonbrander/lettersmith_py#1]
Installing the package locally (through `pip` as an editable package as proposed in the docs) fails with the following traceback:

```
~/Projects/lettersmith_py master (env) % lettersmith_scaffold foo --type wiki
Traceback (most recent call last):
  File "/home/benoit/Projects/lettersmith_py/env/bin/lettersmith_scaffold", line 11, in <module>
    load_entry_point('lettersmith', 'console_scripts', 'lettersmith_scaffold')()
  File "/home/benoit/Projects/lettersmith_py/lettersmith/bin/scaffold.py", line 30, in main
    copy(scaffold_path, project_path, content=True)
  File "/home/benoit/Projects/lettersmith_py/lettersmith/file.py", line 46, in copy
    recursive=recursive, content=content)
  File "/home/benoit/Projects/lettersmith_py/lettersmith/file.py", line 29, in _copy_dir
    return subprocess.check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 323, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rsync': 'rsync'
```

Dependency on rsync should be advertised and explained.

**Comment by gordonbrander** [comment]
@saalaa thanks for catching this. Will look into fallback. Want to avoid implementing copy in Python if possible.

**Comment by gordonbrander** [comment]
Fixed by https://github.com/gordonbrander/lettersmith_py/commit/7d7e0180d8d194de1428259a03f4e533ff4fca6f
