### ISSUE TITLE
Jinja error: no filter named 'where_not'

### ISSUE THREAD

**Issue by saalaa** [gordonbrander/lettersmith_py#2]
Following the docs, running `lettersmith_site lettersmith.yaml` does not work.

It appears that the theme installed from the scaffolding uses `where_not("id_path", id_path)` which does not exist.

```
Traceback (most recent call last):
  File "/home/benoit/Projects/lettersmith_py/env/bin/lettersmith_site", line 11, in <module>
    load_entry_point('lettersmith', 'console_scripts', 'lettersmith_site')()
  File "/home/benoit/Projects/lettersmith_py/lettersmith/bin/site.py", line 158, in main
    stats = Docs.write(docs, output_path=output_path)
  File "/home/benoit/Projects/lettersmith_py/lettersmith/docs.py", line 23, in write
    for doc in docs:
  File "/home/benoit/Projects/lettersmith_py/lettersmith/bin/site.py", line 156, in <genexpr>
    docs = (render_jinja(doc) for doc in docs)
  File "/home/benoit/Projects/lettersmith_py/lettersmith/jinjatools.py", line 123, in render_doc
    template = env.select_template(doc.templates)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/environment.py", line 854, in select_template
    return self._load_template(name, globals)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "theme/wiki/all.html", line 14, in template
    {% for li in index.values() | remove_index | where_not("id_path", id_path) | sort_by("title") %}
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 799, in visit_Template
    self.blockvisit(block.body, block_frame)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 1108, in visit_For
    self.visit(node.iter, frame)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 70, in new_func
    return f(self, node, frame, **kwargs)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 1589, in visit_Filter
    self.visit(node.node, frame)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 70, in new_func
    return f(self, node, frame, **kwargs)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 1578, in visit_Filter
    self.fail('no filter named %r' % node.name, node.lineno)
  File "/home/benoit/Projects/lettersmith_py/env/lib/python3.7/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: no filter named 'where_not'
```

**Comment by gordonbrander** [comment]
@saalaa thanks for catching. Fixed!
