### ISSUE TITLE
Fresh wiki compilation error

### ISSUE THREAD

**Issue by btbytes** [gordonbrander/lettersmith_py#4]
```
lettersmith_site lettersmith.yaml
Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/pyenv-kdlYh41C/bin/lettersmith_site", line 11, in <module>
    load_entry_point('lettersmith', 'console_scripts', 'lettersmith_site')()
  File "/Users/user/src/lettersmith_py/lettersmith/bin/site.py", line 162, in main
    stats = Docs.write(docs, output_path=output_path)
  File "/Users/user/src/lettersmith_py/lettersmith/docs.py", line 23, in write
    for doc in docs:
  File "/Users/user/src/lettersmith_py/lettersmith/bin/site.py", line 160, in <genexpr>
    docs = (render_jinja(doc) for doc in docs)
  File "/Users/user/src/lettersmith_py/lettersmith/jinjatools.py", line 129, in render_doc
    rendered = template.render({"doc": doc})
  File "/Users/user/.local/share/virtualenvs/pyenv-kdlYh41C/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/user/.local/share/virtualenvs/pyenv-kdlYh41C/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/user/.local/share/virtualenvs/pyenv-kdlYh41C/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/.local/share/virtualenvs/pyenv-kdlYh41C/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "theme/wiki/single.html", line 1, in top-level template code
    {% extends "_layout.html" %}
  File "theme/wiki/_layout.html", line 1, in top-level template code
    {% extends "_base.html" %}
  File "theme/wiki/_base.html", line 29, in top-level template code
    {% block body %}{% endblock %}
  File "theme/wiki/_layout.html", line 6, in block "body"
    {% block main %}
  File "theme/wiki/single.html", line 15, in block "main"
    {% for li in backlink_index[id_path] | islice(100) %}
  File "/Users/user/.local/share/virtualenvs/pyenv-kdlYh41C/lib/python3.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'backlink_index' is undefined
```

**Comment by gordonbrander** [comment]
Thanks! Fixed.

Was caused by indexes being moved under `index` template variable, so we can add more indexes in future without worrying about overshadowing global template namespace.
