### ISSUE TITLE
Problem with backlinks in compiling wiki 

### ISSUE THREAD

**Issue by rasoolsomji** [gordonbrander/lettersmith_py#5]
I get the following stacktrace when running lettersmith_site lettersmith.yaml (generated via lettersmith_scaffold . --type wiki)

I'm running Python 3.5.2 on Ubuntu 16.04

```
Traceback (most recent call last):
  File "/usr/local/bin/lettersmith_site", line 9, in <module>
    load_entry_point('lettersmith', 'console_scripts', 'lettersmith_site')()
  File "/var/www/html/lettersmith_py/lettersmith/bin/site.py", line 155, in main
    stats = Docs.write(docs, output_path=output_path)
  File "/var/www/html/lettersmith_py/lettersmith/docs.py", line 23, in write
    for doc in docs:
  File "/var/www/html/lettersmith_py/lettersmith/bin/site.py", line 153, in <genexpr>
    docs = (render_jinja(doc) for doc in docs)
  File "/var/www/html/lettersmith_py/lettersmith/jinjatools.py", line 134, in render_doc
    rendered = template.render({"doc": doc})
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "theme/wiki/single.html", line 1, in top-level template code
    {% extends "_layout.html" %}
  File "theme/wiki/_layout.html", line 1, in top-level template code
    {% extends "_base.html" %}
  File "theme/wiki/_base.html", line 25, in top-level template code
    {% block body %}{% endblock %}
  File "theme/wiki/_layout.html", line 6, in block "body"
    {% block main %}
  File "theme/wiki/single.html", line 11, in block "main"
    {% if index.backlink[doc.id_path] | len %}
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'backlink'
```

**Comment by gordonbrander** [comment]
Thanks! The structure of indexes recently changed, and I missed updating the theme to reflect that. Fixed!
